travis:
  secure:
    BINSTAR_TOKEN: HkUI0Q6C+DNOiDElEUxmF7uzlq9QEJ7PeyPMBP6r2QDGfLsMXZkFv4erwBFBqJT3w+iEIhQgM3ZDARuolcYxuw+N0qGeiOscVsj1KpUd5+eRUM0Tye8dkdiqzqbAPITp8YgsGdqqTfmrGfUEYNwF4pOcndb+dFOjgwwOIYalEO0NRc71XXa+3PZC+SunO7ds01o6oJfkN+uGclxAbha1E6bRL8rJoEf5/LEOZhHHfjER/632d5jsdXQK21oNpFZSMKYvcw5dvNlIOiROvzS/b3OCGdFVUF3o/hjRGSX5QE+cuxygwtmFpR9C+rLcY9B5L/z3WuCq0NszHGQWsn1J+V+bNw2izlg5bJZCTDW/Kn1sfmNjI+e1NyDwod/k277bBkyTPt9elGiCVvR4blLkhsJeHlaWLVCn8LhW6kBuesgVWCs0b0hpVyj0wUAJmnoIm3YCK1XF10VHxKA86IZ3j+QshPHoKBm9DoPPMnwwlmnXJ3+f/7UNuUvZfsERiDzVH4f0WpMXUnqQztd+6s61lq4wTVFigDkjaNtQxtk8/EQWvgCkxNGdC7sm2NeKPkkASK78ON/cXG7G4256++7NIhoqOf7EZFJSkfB4ZqWl3PwXHTeCy5Yd4uslkpz6X6mZ0NDDPppYd4+PcH+wUcEKPhd4PBDPfuQu+qYcEOJN6p8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
